/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.galvanize;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }

    private boolean isEmpty = true;



    public boolean isEmpty(){
        return isEmpty;
    }

    public void addItem(){
        isEmpty = false;
    }
}
